### ISSUE TITLE
I can't import the plugin directly

### ISSUE THREAD

**Issue by vamsinimmala1992** [agile4you/bottle-jwt#15]
ImportError: cannot import name 'JWTProviderPlugin'

I am new using API's, can you help me

**Comment by PyB1l** [comment]
Hi there, could you please provide some code for insight? It seems more like a python environment problem than bottle-jwt.

**Comment by vamsinimmala1992** [comment]
I am just using the example.py file that you have. The error occurs in the first line 

**from bottle_jwt import (JWTProviderPlugin, jwt_auth_required).**

I installed with command pip install bottle_jwt


This is the error:

Traceback (most recent call last):

  File "<ipython-input-1-a757cb18446c>", line 1, in <module>
    from bottle_jwt import (JWTProviderPlugin, jwt_auth_required)

  File "D:\Projects\Decision-Support\Scripts\WebService\bottle_jwt.py", line 7, in <module>
    from bottle_jwt import (JWTProviderPlugin, jwt_auth_required)

ImportError: cannot import name 'JWTProviderPlugin'

**Comment by PyB1l** [comment]
You have written a module with name `bottle_jwt.py` so python interpreter cant  locate installed library.
Try to rename your "D:\Projects\Decision-Support\Scripts\WebService\bottle_jwt.py" file to something else. This is a python related behavior. You will face the exact same problem if you try to name a python module like a build-in module.package or any package you have installed with pip.
