### ISSUE TITLE
Example FakeBackend in readme dont work

### ISSUE THREAD

**Issue by martinrm77** [agile4you/bottle-jwt#4]
You need a better example with the correct function (not get_user, but authenticate_user and get_user) and return a string from authenticate_user instead of dict.

A little bit better documentation on the BaseBackend would also help using this plugin

**Comment by PyB1l** [comment]
Thanks for your notice.You have a point as it seems. I tried it my self and it doesn't work, so i will fix it ASAP. The BaseBackend class is just an interface to implement in order to integrate with the plugin. I think it's better to leave it as an interface rather that using a concrete solution. This way you can use this plugin with any backend system of your choice (SQL, file-system, Redis, etc). Feel free to contribute anytime.

**Comment by martinrm77** [comment]
I have a working example now, I will make a pull request in a few days.

Mvh.
Martin René Mortensen

**Comment by martinrm77** [comment]
Made a pull request to an update to the example.

**Comment by martinrm77** [comment]
Made new pull request to put the example into README as well...
This should close the issue.

**Comment by andr3w321** [comment]
I think when you released v0.2 you forgot to pull in @martinrm77 's pull request locally so when you pushed an update you ended up rolling back his changes.  That or I am running the example wrong.

` curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" --data '{"username": "pav", "password": "123"}' http://localhost:8080/auth`

`File "/home/user/.local/lib/python2.7/site-packages/bottle_jwt/auth.py", line 103, in create_token
    b(user)
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: b2a_base64() argument 1 must be string or buffer, not dict`

**Comment by PyB1l** [comment]
I think that you are probably running the example correct, but version 0.2 don't support  python 2.x (yet!!). Anyway by looking at your error, I also assume that you have an earlier version of **bottle-jwt** installed  (line 103 in bottle_jwt/auth.py contains a docstring in version 0.2).

**Comment by el-aro** [comment]
im trying to implement this, but it does't work, y receive something like this.

>  File "adapter.py", line 54, in <module>
>     ttl=30
>   File "/var/www/smsDecoderEnv/local/lib/python2.7/site-packages/bottle_jwt/auth.py", line 206, in __init__
>     self.provider = JWTProvider(**kwargs)
>   File "/var/www/smsDecoderEnv/local/lib/python2.7/site-packages/bottle_jwt/auth.py", line 61, in __init__
>     raise TypeError('backend instance does not implement {} interface'.format(BaseAuthBackend))
> TypeError: backend instance does not implement <class 'bottle_jwt.backends.BaseAuthBackend'> interface

This is my code
`from models.models import User
from bottle_jwt.backends import BaseAuthBackend

class SQLAlchemyExampleBackend(object):
         def __init__(self):
             self.orm_model = User()
    
         def authenticate_user(self, user_uid, password):
            user = self.orm_model.where(email=user_uid)
            stored_hash = user.password.encode('utf-8')
            if bcrypt.hashpw(password, stored_hash) == stored_hash:
                return user 
            else:
                return None
    
         def get_user(self, user_id):
             return self.orm_model.find(id=user_uid).serialize() or None`

**Comment by PyB1l** [comment]
I just updated master branch to resolve an issue with __subclasshook__ in BaseAuthBackend, and updated PYPI version to 0.7. Nevertheless, your  SQLAlchemyExampleBackend implementation does not conform to BaseAuthBackend interface: Your authenticate method should use (username, password) as signature.

**Comment by PyB1l** [comment]
This is an error from my docstring that i forgot to fix.

**Comment by PyB1l** [comment]
I have fixed docstring in master branch

**Comment by el-aro** [comment]
I actually realice that later, i actually try it to run it commenting that line where it makes that validation, but now i don't need it, Thank you so much, is not working perfectly.
