### ISSUE TITLE
no Attribute signature

### ISSUE THREAD

**Issue by andriwarda** [agile4you/bottle-jwt#7]
Hello i want to implement bottle jwt to authenticate mosquitto client using the broker.
I used python 2.7, when i run bottle its running correctly. The mosquitto configuration too. But when i try to run to publish using username and password using this command `mosquitto_pub -t "test" -m "hola_mundo" -u andri -P andri123`. When i used this command i have some error 
In bottle terminal,
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 189, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 492, in call
    return self._make_callback()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 528, in _make_callback
    callback = plugin.apply(callback, context)
  File "/home/andri/Documents/bottle-jwt/bottle_jwt/auth.py", line 242, in apply
    signature = inspect.signature(callback).parameters
AttributeError: 'module' object has no attribute 'signature'
127.0.0.1 - - [29/Mar/2017 14:44:17] "POST /auth HTTP/1.1" 500 745`

Can you help me about my error ?
Thank's for advance

In mosquitto =

**Comment by PyB1l** [comment]
Hello, add sorry for the delayed answer.This error was not something you did wrong, bottle_jwt project was working only for python > 3.x. But like you others have encountered the same issues due to python 2 compatibility issues, i just pushed version 0.5 (in github and PYPI) that fully supports python  2.7!
